version: "3"

volumes:
  cache:
    driver: local

services:
  redis:
    image: redis:alpine
    restart: always
    volumes: 
      - cache:/data
    ports:
      - '6379:6379'

  api:
    container_name: queue-container
    image: node:16
    working_dir: /usr/src/node-queue
    restart: always
    volumes:
      - ./dist/:/usr/src/node-queue/dist/
      - ./package-lock.json:/usr/src/node-queue/package-lock.json
      - ./package.json:/usr/src/node-queue/package.json
    ports:
      - '3030:3030'
    depends_on:
      - redis
    links:
      - redis
    environment:
      - APP_PORT=3030
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: bash -c "npm ci --production && npm run docker:start"