version: "3"
services:
  api:
    container_name: queue-container
    image: queue-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - '4030:4030'
    environment:
      - APP_PORT=4030
    command: bash -c "npm run dev"